# Generated by Django 4.0.2 on 2022-04-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_pricing_estimator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='houses',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='houses',
            name='lastname',
        ),
        migrations.AddField(
            model_name='houses',
            name='baths_number',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='houses',
            name='floor_number',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='houses',
            name='rooms_number',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='houses',
            name='square_meters',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='houses',
            name='year_construction',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
