# Generated by Django 4.0.2 on 2022-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_pricing_estimator', '0002_houses1_remove_houses_firstname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Houses1',
        ),
        migrations.AlterField(
            model_name='houses',
            name='baths_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='houses',
            name='floor_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='houses',
            name='rooms_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='houses',
            name='square_meters',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='houses',
            name='year_construction',
            field=models.IntegerField(),
        ),
    ]
