# Generated by Django 4.0.2 on 2022-04-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_pricing_estimator', '0003_delete_houses1_alter_houses_baths_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='square_meters',
            field=models.FloatField(),
        ),
    ]
