# Generated by Django 4.0.4 on 2022-06-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_pricing_estimator', '0005_predictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
    ]
